import React from 'react'
import Router from 'next/router';
import Head from 'next/head';
import Web3Modal from "web3modal";
import { ethers } from "ethers";
import * as PushAPI from "@pushprotocol/restapi";

export default function Login() {
  const handleLogin = async (e) => {
    e.preventDefault()

    const web3Modal = new Web3Modal();
    const connection = await web3Modal.connect();
    const provider = new ethers.providers.Web3Provider(connection);
    const signer = provider.getSigner();

    let apiResponse = await PushAPI.channels.subscribe({
      signer: signer,
      channelAddress: 'eip155:5:0x42082772D74F5E48E25f7663D98351C40A9CE9db', // channel address in CAIP
      userAddress: 'eip155:5:' + await signer.getAddress(), // user address in CAIP
      onSuccess: () => {
        console.log('opt in success');
      },
      onError: () => {
        console.error('opt in error');
      },
      env: 'staging'
    })

    Router.push('/home')
  }
  // TODO: Integrate Arcana Login
  return (
    <>
      <Head>
        <title>PeerTask</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative flex flex-col justify-center min-h-screen overflow-hidden">
        <div className="w-full p-6 m-auto bg-[#1a1e27] text-white rounded-md shadow-md lg:max-w-xl">
          <h1 className="text-3xl font-semibold text-center text-[#0284c7]">
            Connect Wallet!
          </h1>
          <form className="mt-6" onSubmit={handleLogin}>
            <div className="mt-6">
              <button className="w-full bg-[#0284c7] text-white text-lg px-5 py-2 rounded-xl">
                Login
              </button>
            </div>
          </form>
        </div>
      </div>
    </>
  );
}